name: WorldTravelersAssociation
favicon: null
layout_spectrum: 1
typography_spectrum: 0.35939
title: 'World Travelers Association '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ed1c24'
    - '#7f1416'
    - '#ffffff'
    - '#f0713d'
    - '#f7ba9e'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: 2aa3f80c-eb61-4648-ade1-0ea9e52456dc
    url: null
