name: WorldTravelersAssociation
favicon: null
layout_spectrum: 1
typography_spectrum: 0.35939
title: 'World Travelers Association '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#200d07'
    - '#d72e0d'
    - '#dd8641'
    - '#fefefe'
    - '#3a6838'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: null
    url: null
